Improve wrapper commands to properly find original commands

diff --git a/bin/docker b/bin/docker
--- a/bin/docker
+++ b/bin/docker
@@ -6,18 +6,27 @@
 #
 # set -x
 
-DOCKER_PATH=""
+# Generic function to get original command path (bypassing wrapper scripts)
+get_original_command() {
+    local cmd="$1"
+    if [ -z "$cmd" ]; then
+        echo "Error: command name required" >&2
+        return 1
+    fi
+    
+    local original_path="$PATH"
+    local script_dir=$(dirname "$0")
+    PATH=$(echo "$PATH" | sed "s|:$script_dir||g" | sed "s|^$script_dir:||g")
+    local cmd_path=$(command -v "$cmd")
+    PATH="$original_path"
+    echo "$cmd_path"
+}
+
+# Get the original docker command
+DOCKER_PATH=$(get_original_command "docker")
 DOCKER_PUSH_DIR="$HOME/.aedev"
 DOCKER_PUSH_LOG="$DOCKER_PUSH_DIR/docker_pushes.txt"
 DOCKER_PULL_LOG="$DOCKER_PUSH_DIR/docker_pulls.txt"
-
-if [ -f "/usr/local/bin/docker" ]; then
-  DOCKER_PATH="/usr/local/bin/docker"
-fi
-if [ -z "$DOCKER_PATH" ]; then
-  echo "Could not find docker installation location."
-  exit 1
-fi
 
 clean() {
   $DOCKER_PATH images  | tr -s ' '  | grep "<none> <none>" | cut -d' ' -f3  | xargs -I {} $DOCKER_PATH rmi {} 
diff --git a/bin/git b/bin/git
--- a/bin/git
+++ b/bin/git
@@ -1,17 +1,24 @@
 #!/bin/bash
 # set -x
 
-GIT_PATH=""
+# Generic function to get original command path (bypassing wrapper scripts)
+get_original_command() {
+    local cmd="$1"
+    if [ -z "$cmd" ]; then
+        echo "Error: command name required" >&2
+        return 1
+    fi
+    
+    local original_path="$PATH"
+    local script_dir=$(dirname "$0")
+    PATH=$(echo "$PATH" | sed "s|:$script_dir||g" | sed "s|^$script_dir:||g")
+    local cmd_path=$(command -v "$cmd")
+    PATH="$original_path"
+    echo "$cmd_path"
+}
 
-if [ -f "/opt/homebrew/bin/git" ]; then
-  GIT_PATH="/opt/homebrew/bin/git"
-elif [ -f "/usr/bin/git" ]; then
-  GIT_PATH="/usr/bin/git"
-fi
-if [ -z "$GIT_PATH" ]; then
-  echo "Could not find git installation location."
-  exit 1
-fi
+# Get the original git command
+GIT_PATH=$(get_original_command "git")
 
 save() {
   current_branch=`git branch --show-current`
diff --git a/bin/mvn b/bin/mvn
--- a/bin/mvn
+++ b/bin/mvn
@@ -15,7 +15,24 @@
 
 set -e
 
-MVN_COMMAND="$M2_HOME/bin/mvn"
+# Generic function to get original command path (bypassing wrapper scripts)
+get_original_command() {
+    local cmd="$1"
+    if [ -z "$cmd" ]; then
+        echo "Error: command name required" >&2
+        return 1
+    fi
+    
+    local original_path="$PATH"
+    local script_dir=$(dirname "$0")
+    PATH=$(echo "$PATH" | sed "s|:$script_dir||g" | sed "s|^$script_dir:||g")
+    local cmd_path=$(command -v "$cmd")
+    PATH="$original_path"
+    echo "$cmd_path"
+}
+
+# Get the original mvn command
+MVN_COMMAND=$(get_original_command "mvn")
 
 style() {
     # Note: Install (at least package phase) is needed.
diff --git a/bin/yarn b/bin/yarn
--- a/bin/yarn
+++ b/bin/yarn
@@ -4,6 +4,25 @@
 # It uses git-ls and md5 hashes to find if any source files changed.
 # The checksum file is stored in the node_modules directory.
 
+# Generic function to get original command path (bypassing wrapper scripts)
+get_original_command() {
+    local cmd="$1"
+    if [ -z "$cmd" ]; then
+        echo "Error: command name required" >&2
+        return 1
+    fi
+    
+    local original_path="$PATH"
+    local script_dir=$(dirname "$0")
+    PATH=$(echo "$PATH" | sed "s|:$script_dir||g" | sed "s|^$script_dir:||g")
+    local cmd_path=$(command -v "$cmd")
+    PATH="$original_path"
+    echo "$cmd_path"
+}
+
+# Get the original yarn command
+YARN_PATH=$(get_original_command "yarn")
+
 ARGS=()
 VERBOSE=false
 FORCE=false
@@ -58,7 +77,7 @@ done
 YARN_COMMAND="${ARGS[0]}"
 YARN_COMMAND_HASH=`echo ${YARN_COMMAND} | md5sum | cut -d' ' -f1`
 CHECKSUM_FILE_PATH="./node_modules/yarn.${YARN_COMMAND_HASH}.checksum"
-YARN_FULL_COMMAND="/opt/node/bin/yarn ${ARGS[*]}"
+YARN_FULL_COMMAND="$YARN_PATH ${ARGS[*]}"
 if [[ -f "$CHECKSUM_FILE_PATH" ]]; then
     OLD_CHECKSUM=`cat $CHECKSUM_FILE_PATH`
     NEW_CHECKSUM=`git ls-files | sort | xargs -I {} cat {} | md5sum | cut -d' ' -f1`
